### ISSUE TITLE
Edit Registration data - Pmtc status not shown

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-path#101]
When updating birth registration details, previous pmtc status is not shown.

**Comment by cagulas** [comment]
Previous selection should be shown, but it shouldn't be editable. The [data dictionary](https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=0) `Editable` column shows which fields should and should not be editable.

**Comment by cagulas** [comment]
Lgtm.
