### ISSUE TITLE
Advanced Search - edit date of birth range

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-path#104]
When editing the date of birth range, the date picker goes back to today's date rather than the selected date

**Comment by cagulas** [comment]
Lgtm.

**Comment by cagulas** [comment]
Actually, let me reopen this. 

It's letting me pick a date in the future. I think we shouldn't allow dates in the future to be selected or dates of more than 5 years ago.

**Comment by ekigamba** [comment]
Disabling dates for more than five years ago - What about when the app is used with children who are more than five years old (Similar to the weight graph problem children) and someone wants to search for such a child?

**Comment by cagulas** [comment]
Good point. Let me talk to PATH team.

**Comment by cagulas** [comment]
Let's go with the future constraint (don't allow dates past today's date) and leave past dates open, i.e. don't put a constraint on the date in the past.

**Comment by ekigamba** [comment]
Cool

**Comment by cagulas** [comment]
Lgtm

**Comment by cagulas** [comment]
This is done, closing.
