### ISSUE TITLE
Out-of-service form can be saved without a service being filled as provided (offered) 

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-path#111]
How to reproduce:

1. Go to Advanced search
2. Select Outside and Inside My Catchment Area - Perform a global search
3. Type 'e' in Last Name
4. Click search
5. From the results, chose one patient. Click on **Record Service**
6. Enter the **Service date** and click **Save**

**Comment by cagulas** [comment]
Lgtm

**Comment by cagulas** [comment]
This is fixed.
