### ISSUE TITLE
Slow and unresponsive app - Opening a child's health details

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-path#124]
How to reproduce:

1. Open the ZEIR app
2. Click on a child
1. Click on the child basic details card/rectangle

The app takes time to open the Health Details page or shows a black screen

**Comment by cagulas** [comment]
Still lagging for me. It doesn't show a black screen, but it's definitely not instantaneous. There is about a 1 second delay between tapping the screen and the action taking place. It's long enough for a user to start double-tapping I think. I find this especially true when going from the Under Five History tab to the Registration Data tab. This is on my Samsung Galaxy Tab S2.

**Comment by faith-mutua** [comment]
@cagulas Mine is also not instantaneous. I am using the same tablet.

**Comment by cagulas** [comment]
Closing this.
