### ISSUE TITLE
Further improve app speed

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-path#130]
Responsive but slow child details page

**Comment by ekigamba** [comment]
Issues found:

1. ListView or related widgets do not reuse views
2. Regex operations & String.replaceAll operations using 21% exclusive CPU time
3. NestedScrollableView makes list view redundant

Probable fixes:

1. Use of recyclerviews and/or Expandable list view which provides ability of reusing views in nested ListView - It is recommended to do away with the NestedListView
2. Use faster libraries for Regex & String operations - Guava, Apache Commons Lang & Custom Java Algorithms. These libraries are faster for some operations and not all in comparison to standard java API provided for the same.
3. Reduce for loops & Db updates/RowGroup updates performed for each vaccine rendered

NB: ExpandableListView **might** be a bit laggy when all groups are expanded even those not visible on the list

**Comment by mberg** [comment]
Which views on the app do these apply to. Just the details page? Would be
good to know what parts of the app the above affect.

**Comment by ekigamba** [comment]
Cool, will add that

**Comment by cagulas** [comment]
This is done, closing.
