### ISSUE TITLE
Child's residential area not showing up correctly for some patients

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-path#131]
![screenshot_20171017-135409](https://user-images.githubusercontent.com/31766075/31664001-786876a6-b34c-11e7-8e3f-a11040c57010.png)
![screenshot_20171017-135428](https://user-images.githubusercontent.com/31766075/31664003-78d029cc-b34c-11e7-8936-367f51924b40.png)
![screenshot_20171017-135442](https://user-images.githubusercontent.com/31766075/31664004-7901734c-b34c-11e7-8bdc-f8edd359a511.png)
![screenshot_20171017-135455](https://user-images.githubusercontent.com/31766075/31664005-793357ea-b34c-11e7-816a-5c43bb0999c0.png)
![screenshot_20171017-135540](https://user-images.githubusercontent.com/31766075/31664007-7965752c-b34c-11e7-95cb-ca5125883932.png)
![screenshot_20171017-135601](https://user-images.githubusercontent.com/31766075/31664008-79c56400-b34c-11e7-9333-866f2520a8a1.png)

**Comment by cagulas** [comment]
Lgtm

**Comment by cagulas** [comment]
This isn't an issue anymore, closing.
