### ISSUE TITLE
A user cannot edit weight without changing the date when weight was recorded

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#135]
When editing weight, the app does not allow a user to save the change until the date is changed as well. One has to re-select the date before saving the changes.

**Comment by cagulas** [comment]
For this one, I think we need to show the "Set" option for instances where they just need to edit the weight in kgs and not the date. Currently, the "Set" only appears after you select "Change date weighed". The user should be able to save or "Set" the weight even if they only edit the weight.

**Comment by cagulas** [comment]
This is done.
