### ISSUE TITLE
Stock Issued form crashes when a decimal value is entered in the Vials issued or Vials wasted field

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-path#156]
How to replicate:

1. Go to the Vials issued form
1. Enter a decimal value is either the Vials issued field or the Wasted vials field

**Comment by cagulas** [comment]
Decimals shouldn't be allowed for either of these fields.  See the data dictionary [here](https://docs.google.com/spreadsheets/d/1luD3r_1AQaCn6W-WlgtXilf5PyHJo8qgqZk4FVHxT8w/edit#gid=1075761441) - Integer fields.

**Comment by cagulas** [comment]
Blocked by https://github.com/OpenSRP/opensrp-client-native-form/issues/10

**Comment by cagulas** [comment]
Lgtm. Decimals can no longer be used in any of the three stock forms.

**Comment by cagulas** [comment]
Closing this, this is done.
