### ISSUE TITLE
Add remaining Coverage and Dropout Report assets

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#170]
- [x] Coverage Reports icon for side menu
- [x] Dropout Reports icon for side menu
- [ ] <del>Coverage Reports selection screen (similar to `Dropout01-Menu` screen in InVision, but for the Coverage Reports)</del>

**Comment by rowo** [comment]
First two boxes:

![zeir-menu](https://user-images.githubusercontent.com/1584163/33329691-0b1c1e72-d42b-11e7-9569-3101337c7220.png)
![icon-menu-coverage](https://user-images.githubusercontent.com/1584163/33329692-0b3363c0-d42b-11e7-8efc-bcc7b92fc004.png)
![icon-menu-dropout](https://user-images.githubusercontent.com/1584163/33329693-0b3e8fe8-d42b-11e7-8c23-d600d0a1f437.png)

**Comment by rowo** [comment]
@cagulas what goes into the Coverage reports selection screen? Do I need to make a mockup or is just an updated icon okay? 

Also note I made an updated icon for the Dropout Report (missing person) from the Dropout Menu selection screen (dot dot X). Which one do you think works best?

**Comment by cagulas** [comment]
Have created the implementation issues for these. Also, have added a note to use this dropout icon instead of the original one in the dropout selection screen issue. Closing this.
