### ISSUE TITLE
Implement the Cohort Coverage Report

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#171]
![252795239](https://user-images.githubusercontent.com/3488986/33122607-c2fed6f8-cf88-11e7-8307-8ecfa5717848.png)

Please also see "Coverage Report" tab in the [reporting dictionary](https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=705615058), second row, No. 1, "Cohort coverage report" for the indicator calculations.

Overview: The cohort vaccination coverage report is the percentage of children within the same cohort (e.g. living in a certain area and were born in a certain timeframe), that were vaccinated with a certain vaccine dose. Kids drop out of the cohort if they die or move to a different catchment area. They remain in the cohort if they are marked as inactive or lost to followup in ZEIR.

- [x] Tapping the back button in the top left or the back button on the tablet takes the user back to the Coverage Report selection screen.
- [x] The Cohort field at the top is a dropdown, where the user can select which cohort (month-year) to view. Only show the cohorts in the dropdown that have alive children registered in the app for that health facility. E.g. If there are no children registered for a health facility who are alive and born in January 2017, do not show January 2017 in the dropdown.
- [x] Cohort size is the current size of the cohort, i.e. the number of children who are registered at that health facility who were born in a particular calendar month. Since users can go back and register older children in the app and children can move into the health facility area, this number can increase over time. This number can also decrease over time if children die or are moved to a different health facility. **This is the denominator for the coverage rate**.
- [x] All vaccine doses are listed on the page as shown in the mockup "Vaccine" column.
- [x] The "Vaccinated" column shows the total number of children in the cohort who received that particular vaccine dose within the allowed timeframe (see reporting dictionary for the timeframes). **This is the numerator for the coverage rate**.
- [x] The "Coverage" column shows the coverage rate for that particular vaccine dose and cohort. This is the number vaccinated divided by the number of children in the cohort multiplied by 100 and displayed as a percentage (whole number).
- [x] The number vaccinated and the coverage percentage are changed to blue font when they are finalized (see reporting dictionary for the timeframes for when these are finalized).

**Comment by cagulas** [comment]
Results from QA on 29 January (V1.3.2.1):

- [ ] When I marked a patient as deceased, he wasn't deducted from the January 2018 cohort coverage report. Dummy patient (https://openmrs.zeir-stage.smartregister.org/openmrs/patientDashboard.form?patientId=47359&phrase=emojiji) was a part of the January 2018 cohort. I submitted a report child deceased form, and the cohort coverage reports should have updated. E.g. the cohort size, bcg, and opv 0, should have been reduced by 1. This didn't happen.

**Comment by faith-mutua** [comment]
Results from QA on 1 Feb (V1.3.2.1):

- [ ] The number vaccinated and coverage rates for some vaccines have not yet become finalized even though the given timeframe for them to be finalized has lapsed. e.g. BCG coverage for January 2017 should have been finalized on February 1, 2018.  The number vaccinated and the coverage percentage have not yet changed to the blue font. 

- [ ] When I move a child out of the area or mark them as deceased, their previous vaccines are not subtracted from the number Vaccinated and Coverage rate.

**Comment by cagulas** [comment]
@faith-mutua Can you QA the above issues again? Go ahead and close the issue if they are all resolved.

**Comment by faith-mutua** [comment]
This looks good now. Closing the issue.
