### ISSUE TITLE
Implement the Set CSO Under 1 Population input window

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#172]
![coverage-annual-coverage-report-cso-nonumber-annualcso-and-facility-cum](https://user-images.githubusercontent.com/1584163/33338247-772dbc84-d443-11e7-8403-39753b43da62.png)

Please also see "Coverage Report" tab in the [reporting dictionary](https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=705615058), third row, No. 2, "Annual coverage report - CSO" for reference.

Overview: This is the number that each health facility receives from Zambia's Central Statistics Office (CSO) that they use as a denominator to calculate coverage rates. A user at each health facility needs to type in the CSO number for each calendar year in the app. 

- [x] This input window pops up the first time the user opens the "Annual coverage report - CSO" page in the Coverage Reports module in the app. The current calendar year is what should display as the default. So right now, only 2017 calendar year will be displayed, but on January 1, 2018, the calendar year 2018 should appear in the dropdown as well, and this input window will pop up when they visit this report page starting Jan 1, 2018.
- [x] Where it says "[clinic name]", populate the name of the health facility for the logged-in user.
- [x] Tapping "OK" saves the number and it updates the CSO Target number (for that particular calendar year) that is displayed in the "Annual coverage report - CSO" and the "Facility Cumulative Coverage Report" reports.
- [x] Tapping "Cancel" or tapping anywhere outside the window closes the window without saving the changes.
- [x] The user can reopen the input window by tapping the "CSO Target" area on the "Annual coverage report - CSO" report page. @rowo Do we need to indicate that this area is tappable?
- [x] If no CSO target number is inputted (i.e. left blank), then the "Annual coverage report - CSO" and the "Facility Cumulative Coverage Report" report pages will be blank.

**Comment by rowo** [comment]
@cagulas I think the year should be in the popup and not rely on the background. Where would the text be updated?

**Comment by cagulas** [comment]
Maybe "Set CSO Under 1 Population - 2017" ??

**Comment by rowo** [comment]
Marked as blocked to do following:
- design "edit" button for an entered CSO number
- define whether a blank state exists and what's on it if it does
- further define behaviors when CSO number is updated or removed, and rules around edit

**Comment by rowo** [comment]
More detail around how CSO target works.

1. If a CSO target isn't defined for the current time period selected in the dropdown (default is always landing on the current time period), a popup appears when you go to the report page:

![cso01](https://user-images.githubusercontent.com/1584163/33613170-e70c70aa-d9a1-11e7-8ae1-ab0bc9879600.png)

Relatedly, if you try to select another time period in the dropdown and the CSO target isn't defined for that time period, you get the same pop up.

2. If you cancel out of the popup without entering a CSO target, you'll see a screen like this:

![cso02](https://user-images.githubusercontent.com/1584163/33613234-14db9ff6-d9a2-11e7-886f-9d82925fa78d.png)

Note you can see the number vaccinated but it doesn't give you a coverage.

3. After filling out the CSO target, you can see the coverage rate:

![cso03](https://user-images.githubusercontent.com/1584163/33613280-38e26736-d9a2-11e7-8340-e0225f599fe0.png)

As mentioned, if you go to another time period in the dropdown, it will react similarly with regards to a missing CSO target value. All CSO targets are editable at any time by hitting the "Edit" icon to the right of the CSO Target number, and that popup appears again and acts like described in the first comment. 

@cagulas Is it a requirement to be able to remove the CSO target once entered by deleting the number in the edit popup and hitting ok? If not, we'll need an error message to say "cannot be left blank" with the app remembering if something was already entered. And if something was not already entered, you can leave it blank.

**Comment by cagulas** [comment]
@rowo Thanks for this. This looks great to me. It's not a req to be able to remove the CSO target, and I can't think of a reason why this would be much added value. If they make a mistake when entering the number, they should edit it to the correct number, and if they don't know the correct number (i.e. they were just playing around with coverage figures by inputting various targets), then they can always edit it again later when they do know the correct number. 

Having said that, allowing them to delete the number and go back to the blank state might be easier than having the app remember if there was a previous input or not, so I'll let @keymane and @manutarus weigh in here.

**Comment by keymane** [comment]
I think adding an error message is better than allowing the user to delete the previous CSO target value.

**Comment by cagulas** [comment]
Sounds good. The error message can be: "CSO target cannot be blank." It can appear only if they delete the value and try to save.

**Comment by cagulas** [comment]
Looks great!
