### ISSUE TITLE
Implement the Annual Coverage Report - CSO

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#173]
![252795237](https://user-images.githubusercontent.com/3488986/33125312-0e2a8d86-cf91-11e7-92c9-24cdd25fad2c.png)

Please also see "Coverage Report" tab in the [reporting dictionary](https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=705615058), third row, No. 2, "Annual coverage report - CSO" for reference.

Overview: The annual CSO coverage rate is measured by comparing the number of children vaccinated with a particular vaccine dose and the number in the target population of surviving infants under one year of age (these are the eligible infants) provided by the CSO. The result is expressed as a percentage.

- [x] Tapping the back button in the top left or the back button on the tablet takes the user back to the Coverage Report selection screen.
- [x] The Year field at the top is a dropdown, where the user can select which calendar year to view. Only 2017 will be an option for now. On January 1, 2018, 2018 should get added to the dropdown.
- [x] CSO Target is the number that the user enters for that calendar year in the input window (https://github.com/OpenSRP/opensrp-client-path/issues/172). **This is the denominator for the coverage rate**.
- [x] All vaccine doses are listed on the page as shown in the mockup "Vaccine" column. Please note, in the mockups, Measles 2 / MR 2 vaccine dose gets cut off. It should be included here.
- [x] The "Vaccinated" column shows the total number of children in the app (within the allowed age range) who received that particular vaccine dose within the calendar year (see reporting dictionary for the age range). **This is the numerator for the coverage rate**.
- [x] The "Coverage" column shows the coverage rate for that particular vaccine dose using the CSO number. This is the number vaccinated divided by the number of children in the CSO multiplied by 100 and displayed as a percentage (whole number).
- [x] In the Year field, the "(In Progress)" label gets added if the calendar year has not finished yet. For e.g. 2017 will show "(In Progress)" until January 1, 2018 and so on. When finalized, the coverage numbers can change to blue font (not pictured here, but pictured in https://github.com/OpenSRP/opensrp-client-path/issues/174).
- [x] Each vaccine dose row can be tapped to open the "Facility Cumulative Coverage Report" page for that vaccine dose (issue to be created).

**Comment by cagulas** [comment]
Results from QA on 31 January (V1.3.2.1):

- [ ] As soon as you open this report, the keypad pops up. Keypad should only pop up when you open the CSO target entry window.
- [ ] The number shown in the Vaccinated column should change to blue font as well when it gets finalized. If you look at 2017, only the coverage percentage is in blue font.
- [ ] Penta 3 row should open the same facility cumulative coverage chart as Penta 1. Right now it shows Penta 3 + 3 placeholder. Same goes for Measles 1. It should be same as BCG.

@rowo I'm thinking that we should show some indication that these rows are tappable and open the facility cumulative coverage report for that indicator. Any thoughts?

**Comment by rowo** [comment]
@cagulas Sure, we could add an icon at the left-front of the row. Maybe https://material.io/icons/#ic_description or https://material.io/icons/#ic_open_in_browser or https://material.io/icons/#ic_open_in_new or https://material.io/icons/#ic_pageview would be okay with me.

**Comment by cagulas** [comment]
I think pageview or open in new (last two links you provided) make the most sense to me.

@keymane what do you think?

**Comment by keymane** [comment]
@cagulas okay, makes sense. Where should the indicator be added? left or right side

**Comment by rowo** [comment]
Left

**Comment by keymane** [comment]
okay

**Comment by faith-mutua** [comment]
Results from QA on 1 February (V1.3.2.1):

- [ ] An error should be thrown when 0 value is entered as a CSO Target. When a user enters 0 value, then clicks OK, the CSO Target window closes then opens again when defining the target for the first time. If editing the target, the previous value is retained. 

- [ ] Previous years should be in blue font and finalized. Currently, 2017 which is the previous year is in black font and only the Coverage rates are finalized. The number Vaccinated are still in black font.

**Comment by cagulas** [comment]
@faith-mutua This is ready to QA again. I checked everything except for your last point:

>Vaccinated number increases when a child moves into the area. The number should not be affected if a child is marked as deceased or moves out of the area or moves into the area (unless they receive new vaccines after they move into the area)

Can you test the above again?

**Comment by faith-mutua** [comment]
@keymane This hasn't been fixed yet. 

>Vaccinated number increases when a child moves into the area. The number should not be affected if a child is marked as deceased or moves out of the area or moves into the area (unless they receive new vaccines after they move into the area)

**Comment by faith-mutua** [comment]
Lgtm.
