### ISSUE TITLE
Implement the Annual Coverage Report - ZEIR

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#174]
![252795238](https://user-images.githubusercontent.com/3488986/33125845-3eb94e68-cf93-11e7-8084-209a372a9cf8.png)

Please also see "Coverage Report" tab in the reporting dictionary, fourth row, No. 3, "Annual coverage report - ZEIR" for reference.

Overview: The annual ZEIR coverage rate is measured by comparing the number of children vaccinated with a particular vaccine dose and the number in the target population of surviving infants under one year of age (these are the eligible infants) as registered in ZEIR. The result is expressed as a percentage.

- [x] Tapping the back button in the top left or the back button on the tablet takes the user back to the Coverage Report selection screen.
- [x] The Year field at the top is a dropdown, where the user can select which calendar year to view. Only 2017 will be an option for now. On January 1, 2018, 2018 should get added to the dropdown.
- [x] ZEIR Target is the total number of alive children <= 12 months of age [Date_Birth] currently registered in ZEIR for that health facility (this will change over time as health facilities work to register all of the children in their catchment area in the ZEIR app; children will also grow past 1 year of age or move to a different catchment area or can pass away, and would be removed from this count). **This is the denominator for the coverage rate**.
- [x] All vaccine doses are listed on the page as shown in the mockup "Vaccine" column. 
- [x] The "Vaccinated" column shows the total number of children in the app (within the allowed age range) who received that particular vaccine dose within the calendar year (see reporting dictionary for the age range). **This is the numerator for the coverage rate**.
- [x] The "Coverage" column shows the coverage rate for that particular vaccine dose using the ZEIR target number. This is the number vaccinated divided by the number of children in the ZEIR Target multiplied by 100 and displayed as a percentage (whole number).
- [x] In the Year field, the "(In Progress)" label gets added if the calendar year has not finished yet (not pictured here but pictured in https://github.com/OpenSRP/opensrp-client-path/issues/173). For e.g. 2017 will show "(In Progress)" until January 1, 2018 and so on. When finalized, the coverage numbers can change to blue font (as pictured here).

**Comment by faith-mutua** [comment]
Results from QA on 29 January (V1.3.2.1):

No issues found. lgtm

**Comment by faith-mutua** [comment]
Results from QA on 2 February (V1.3.2.1):

- [ ] Vaccinated number increases when a child moves into the area. The number should not be affected if a child is marked as deceased or moves out of the area or moves into the area (unless they receive new vaccines after they move into the area)

**Comment by cagulas** [comment]
@faith-mutua Can you QA this again? Go ahead and close the issue if it's fixed.

**Comment by faith-mutua** [comment]
@keymane This hasn't been fixed. 

>Vaccinated number increases when a child moves into the area. The number should not be affected if a child is marked as deceased or moves out of the area or moves into the area (unless they receive new vaccines after they move into the area)

**Comment by faith-mutua** [comment]
Lgtm.
