### ISSUE TITLE
Implement the Facility Cumulative Coverage Report

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#175]
![252795240](https://user-images.githubusercontent.com/3488986/33126304-1395bb2a-cf95-11e7-89d6-a942997a0bce.png)

Please also see "Coverage Report" tab in the reporting dictionary, fifth row, No. 4, "Facility Cumulative Coverage Report " for reference.

Overview: For a particular vaccine dose, this indicator calculates the cumulative monthly percentage of immunized children compared to the cumulative number of surviving infants in the target population for a particular calendar year (using CSO target number). The result is expressed as a percentage and charted on a graph by month for a full calendar year.

- [x] The user opens this chart from the row of the vaccine dose in the Annual Coverage Report - CSO page (https://github.com/OpenSRP/opensrp-client-path/issues/173). Please note, for this chart, Penta 1 and Penta 3 are combined, as are BCG and Measles 1 / MR 1, to be able to show the dropout between these doses. What this means practically is that all vaccine doses are displayed on their own chart, with the exception of Penta1/3 and BCG/Measles1/MR1 which are displayed on the same chart. On the Annual Coverage Report - CSO page, this means that if the user taps on either Penta 1 or Penta 3 row, they go to the same chart, and same with BCG or Measles 1 / MR 1 rows.
- [x] Tapping the back button in the top left or the back button on the tablet takes the user back to the Annual Coverage Report - CSO page.
- [x] The chart is plotted and the table below it populated as per the formulas and instructions in the reporting data dictionary.

**Comment by cagulas** [comment]
Results from QA on 6 Feb:

- [ ] Can we remove the data point at 0? This is just showing where it's starting, the 0 should not be shown as data point itself.
- [ ] Is there a way to align the x-axis months with the table column months below (as shown in the mockups)? Is this not possible? It looks a little off-centered like this.
- [ ] Thick grey bar is shown on the right side of the table below. Can this be the same width as the rest of the table?
- [ ] If you swipe across the chart, the calendar months on the x-axis somehow slide off the screen. They should be static.
- [ ] The back arrow should take you back to the Annual Coverage Report - CSO page. Right now it goes back to the Coverage report selection screen.
- [ ] BCG should be capitalized in the table below the chart. Same goes for all OPVs, PCVs, 
- [ ] Can we add some space below the table at the bottom, so see the border line at the bottom of the table?
- [ ] On Penta 1/3, add a space in the table: "Drop Out[space](1-3)"

**Comment by keymane** [comment]
@cagulas it may not be possible to align the graph and table below since they are different widgets

**Comment by cagulas** [comment]
@keymane ok thanks. @rowo any changes we should make with this knowledge now?

**Comment by rowo** [comment]
@keymane @cagulas could try to break them apart and get them as close as we can. In that case, the x-axis labels and table header/first row labels should be repeated on both chart and table. This seems acceptable anyways because new rows were added to the bottom table so seeing both on screen at the same time is not going to be possible.

Also, side note, the zero on the chart is off.

**Comment by rowo** [comment]
Here is a screenshot of what's currently in the apk:

![coverage-charts](https://user-images.githubusercontent.com/1584163/35987077-cd9daf80-0cc8-11e8-8d84-0bd2dde267ad.png)

I guess it's okay, just buggy.

**Comment by faith-mutua** [comment]
Lgtm.

**Comment by cagulas** [comment]
- [ ] The line should start at 0. Is not possible to do without showing a data point at 0 as well?
- [ ]  Thick grey bar is shown on the right side of the table below. Still there.
- [ ]  The calendar months on the x-axis are still sliding a bit. Can we align them to the middle of the grid-column initially when the screen loads?
- [ ] Please capitalize the first letter in "Measles 1" , "Penta 1", "Penta 3", "Rota 1", "Rota 2", "Measles 2"

**Comment by cagulas** [comment]
Lgtm.
