### ISSUE TITLE
Implement the BCG-Measles Cumulative Dropout Report

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#177]
![252795242](https://user-images.githubusercontent.com/3488986/33160488-f693d950-d02d-11e7-81ba-fb103f0919e8.png)

Please also see "Dropout Report" tab in the [reporting dictionary](https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=1991837752), second row, No. 1, "BCG - Measles Dropout - Cumulative" for reference.

Overview: Comparison between number of children who start the immunization schedule (BCG) against the number who complete it (Measles 1 or MR 1).

- [x] Tapping the back button in the top left or the back button on the tablet takes the user back to the Dropout Report selection screen (https://github.com/OpenSRP/opensrp-client-path/issues/176).
- [x] The dropout rates are grouped by calendar year (years are listed in reverse chronological order) and by calendar month (months are listed in chronological order, though). 
- [x] The "Month" column lists the calendar months in the year. For the current year (e.g. 2017), a new month row gets added on the first of that month. For e.g. the November row for 2017 would appear on November 1, 2017 and so on.
- [x] The "(Started - Completed) / Started" column shows the number of kids who dropped out between BCG and Measles 1 / MR 1 divided by the number of kids who started the schedule by receiving BCG. In the mockup above, the "14" number is the calculated number of BCG - Measles 1 / MR 1 kids for that month in the app. The "100" number in the mockup above is the number of kids who started the schedule with BCG that month. 
- [x] The "Dropout Percent" column is the 14/100 as a percentage.
- [x] The "Cumulative Dropout (YTD): 14%" just underneath the calendar year is the cumulative dropout percent for all of the months. So in the mockup above for 2017, this would be calculated by adding all dropout kids from all months so far (i.e., 14 in Jan, 14 in Feb, and so on) and dividing by the total number of kids who started BCG from all months so far (i.e., 100 in Jan, 100 in Feb, and so on).

**Comment by faith-mutua** [comment]
Results from QA on 5 February (V1.3.2.1):

- [ ] Months for the year 2017 are listed in reverse chronological order.

**Comment by cagulas** [comment]
@faith-mutua The testing scripts for this look good. I added a couple more. Please go ahead and finish QA.

**Comment by faith-mutua** [comment]
Lgtm

**Comment by cagulas** [comment]
- [ ] The Month / Started/Completed/Dropout Percent row should be in a different font (see mockups) to differentiate the column headings from the data below. This doesn't look like it was done.

**Comment by cagulas** [comment]
Done.
