### ISSUE TITLE
Implement the BCG-Measles Cohort Dropout Report

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#178]
![dropout03-bcgmeaslescohort](https://user-images.githubusercontent.com/1584163/33344398-e17ef806-d456-11e7-9739-9d0a208bbd75.png)

Please also see "Dropout Report" tab in the [reporting dictionary](https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=1991837752), third row, No. 2, "BCG - Measles Dropout - Cohort" for reference.

Overview: Comparison between number of children who start the immunization schedule (BCG) in a cohort against the number who complete it (Measles 1 or MR 1).

- [x] Tapping the back button in the top left or the back button on the tablet takes the user back to the Dropout Report selection screen (https://github.com/OpenSRP/opensrp-client-path/issues/176).
- [x] The dropout rates are reverse chronological order and grouped by calendar year. 
- [x] The "Cohort" column lists the cohort calendar months in the year. For the current year (e.g. 2017), a new cohort month row gets added on the first of that month. For e.g. the November 2017 row would appear on November 1, 2017 and so on.
- [x] The "(Cohort Size - M/MR 1) / Cohort Size" column shows the number of kids in the cohort who dropped out between BCG and Measles 1 / MR 1 divided by the number of kids who started in the cohort. In the mockup above, the "14" number is the calculated number of kids in the cohort minus the number in the cohort who received Measles 1 / MR 1. The "100" number in the mockup above is the number of kids in that cohort. 
- [x] The "Dropout Percent" column is the 14/100 as a percentage.
- [x] The font color is grey if the dropout percent calculation is in progress, and it turns to blue font when it's finalized (see the reporting dictionary for more information on when these become finalized). Due to how dropout coverage is displayed and calculated, the first 12 rows will always be in progress and grey.

**RW: resolved** ~~@rowo I think the blue font is not accurate in the above mockup. Each cohort is followed for a period of one year, because they have one year basically to get BCG and Measles 1 / MR 1 to be counted here, so the dropout becomes final at one year after the cohort is created. So, for example, the May 2017 cohort is created on May 1, 2017. All babies born in May 2017 (up to and including babies born on May 31, 2017) and who receive BCG within their first year of age are added to the cohort. They follow them to see which of them also receive Measles 1 or MR 1 in their first year of age. That means the cohort dropout rate is finalized on June 1, 2018 (because the babies born on May 31, 2017 have until May 31, 2018 to receive BCG and Measles 1 / MR 1). So in the mockup above, all of the 2017 dropout rates would still be in progress and should be grey.~~

**Comment by rowo** [comment]
@cagulas So would another way to be accurate is if all the dates shown in the mockup were 2016 and 2015 — if it were currently June 1, 2017?

**Comment by cagulas** [comment]
@rowo No, because we would show the 2017 months as in progress (grey). 

I do have a question for @keymane though about when the cohort rows should be added. Should the new cohort month get added on the 1st of the month or only when the cohort is created, i.e. the first baby born in that calendar month is vaccinated with BCG and joins the cohort? I was thinking the latter, because you can't calculate the dropout rate with a denominator of zero (no babies are in that month's cohort yet), right?

**Comment by rowo** [comment]
Discussed with Carolyn, I will update so entire list is reverse chronological and so top 12 rows will always be in progress. The newest cohort will always be row 1.

**Comment by keymane** [comment]
@cagulas I also think when a child is born on the calendar month makes more sense

**Comment by cagulas** [comment]
@keymane Sorry, what are you responding to here? It's been a few months, so might need to quickly discuss tomorrow.

**Comment by cagulas** [comment]
Results from QA on 6 Feb:

- [ ] Change "Month" heading to "Cohort"

**Comment by cagulas** [comment]
@faith-mutua Testing scripts look great. You can go ahead and QA this report now.

**Comment by faith-mutua** [comment]
@cagulas okay, thanks

**Comment by faith-mutua** [comment]
Lgtm

**Comment by cagulas** [comment]
- [ ] The cohort row should be a lighter font than the month rows below it. This doesn't look like it's done.

**Comment by cagulas** [comment]
Done
