### ISSUE TITLE
Implement the Penta Cumulative Dropout Report

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#179]
![252795244](https://user-images.githubusercontent.com/3488986/33161513-11b436ba-d035-11e7-9c96-f0ce66f4993a.png)

Please also see "Dropout Report" tab in the [reporting dictionary](https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=1991837752), fourth row, No. 3, "Penta Dropout - Cumulative" for reference.

Overview: Comparison between number of children who start the Penta immunization schedule (Penta 1) against the number who complete it (Penta 3).

- [x] Tapping the back button in the top left or the back button on the tablet takes the user back to the Dropout Report selection screen (https://github.com/OpenSRP/opensrp-client-path/issues/176).
- [x] The dropout rates are grouped by calendar year (years are listed in reverse chronological order) and by calendar month (months are listed in chronological order, though). 
- [x] The "Month" column lists the calendar months in the year. For the current year (e.g. 2017), a new month row gets added on the first of that month. For e.g. the November row for 2017 would appear on November 1, 2017 and so on.
- [x] The "(Started - Completed) / Started" column shows the number of kids who dropped out between Penta 1 and Penta 3 divided by the number of kids who got Penta 1. In the mockup above, the "14" number is the calculated number of Penta 1 - Penta 3 kids for that month in the app. The "100" number in the mockup above is the number of kids who got Penta 1 that month. 
- [x] The "Dropout Percent" column is the 14/100 as a percentage.
- [x] The "Cumulative Dropout (YTD): 14%" just underneath the calendar year is the cumulative dropout percent for all of the months. So in the mockup above for 2017, this would be calculated by adding all dropout kids from all months so far (i.e., 14 in Jan, 14 in Feb, and so on) and dividing by the total number of kids who got Penta 1 from all months so far (i.e., 100 in Jan, 100 in Feb, and so on).

**Comment by cagulas** [comment]
@faith-mutua Testing scripts look good. Please go ahead and QA this issue.

**Comment by faith-mutua** [comment]
- [ ] Months are listed in reverse chronological order. 

- [ ] The Month/(Started - Completed)/Started/Dropout rate should be in a lighter font.

**Comment by faith-mutua** [comment]
Lgtm

**Comment by cagulas** [comment]
- [ ] The Month/(Started - Completed)/Started/Dropout rate should be in a lighter font (see mockups) to differentiate the column headings from the data below. This doesn't look like it's done. Might need to make it lighter.

**Comment by cagulas** [comment]
Done
