### ISSUE TITLE
Implement the Penta Cohort Dropout Report

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#180]
![252795245](https://user-images.githubusercontent.com/3488986/33161629-c53cfd3e-d035-11e7-9106-97c8488b170b.png)

Please also see "Dropout Report" tab in the [reporting dictionary](https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=1991837752), fifth row, No. 4, "Penta Dropout - Cohort" for reference.

Overview: Comparison between number of children who start the Penta immunization schedule in a cohort (Penta 1) against the number who complete it (Penta 3).

- [x] Tapping the back button in the top left or the back button on the tablet takes the user back to the Dropout Report selection screen (https://github.com/OpenSRP/opensrp-client-path/issues/176).
- [x] The dropout rates are grouped by calendar year (years are listed in reverse chronological order) and by cohort calendar month (months are listed in chronological order, though). 
- [x] The "Cohort" column lists the cohort calendar months in the year. For the current year (e.g. 2017), a new cohort month row gets added on the first of that month. For e.g. the November 2017 row would appear on November 1, 2017 and so on.
- [x] The "(Cohort Size - Penta 3) / Cohort Size" column shows the number of kids in the cohort who dropped out between Penta 1 and Penta 3 divided by the number of kids who started in the cohort. In the mockup above, the "14" number is the calculated number of kids in the cohort minus the number in the cohort who received Penta 3. The "100" number in the mockup above is the number of kids in that cohort. 
- [x] The "Dropout Percent" column is the 14/100 as a percentage.
- [x] The font color is grey if the dropout percent calculation is in progress, and it turns to blue font when it's finalized (see the reporting dictionary for more information on when these become finalized).
- [x] Dropout rates are grey if they're in progress and turn to blue font when they're finalized. See comment to @rowo in https://github.com/OpenSRP/opensrp-client-path/issues/178 issue for more context.

**Comment by cagulas** [comment]
Results from QA on 6 Feb:

- [ ] Change "Month" to "Cohort" and make this row a lighter font than the month rows underneath.

**Comment by cagulas** [comment]
@faith-mutua Testing scripts look good. Please go ahead and QA this issue.

**Comment by faith-mutua** [comment]
This looks good to me.

**Comment by cagulas** [comment]
[ ] make this row a lighter font than the month rows underneath.

**Comment by cagulas** [comment]
Done
