### ISSUE TITLE
Implement the Measles Cumulative Dropout Report

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#181]
![252795246](https://user-images.githubusercontent.com/3488986/33161729-7f3674c2-d036-11e7-988a-afdc463491b7.png)

Please also see "Dropout Report" tab in the [reporting dictionary](https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=1991837752), sixth row, No. 5, "Measles Dropout - Cumulative" for reference.

Overview: Comparison between number of children who receive Measles 1 / MR 1 against the number who receive Measles 2 / MR 2.

- [x] Tapping the back button in the top left or the back button on the tablet takes the user back to the Dropout Report selection screen (https://github.com/OpenSRP/opensrp-client-path/issues/176).
- [x] The dropout rates are grouped by calendar year (years are listed in reverse chronological order) and by calendar month (months are listed in chronological order, though). 
- [x] The "Month" column lists the calendar months in the year. For the current year (e.g. 2017), a new month row gets added on the first of that month. For e.g. the November row for 2017 would appear on November 1, 2017 and so on.
- [x] The "(Started - Completed) / Started" column shows the number of kids who dropped out between Measles 1 / MR 1 and Measles 2 / MR 2 divided by the number of kids who got Measles 1 / MR 1. In the mockup above, the "14" number is the calculated number of Measles 1 / MR 1 - Measles 2 / MR 2 kids for that month in the app. The "100" number in the mockup above is the number of kids who got Measles 1 / MR 1 that month. 
- [x] The "Dropout Percent" column is the 14/100 as a percentage.
- [x] The "Cumulative Dropout (YTD): 14%" just underneath the calendar year is the cumulative dropout percent for all of the months. So in the mockup above for 2017, this would be calculated by adding all dropout kids from all months so far (i.e., 14 in Jan, 14 in Feb, and so on) and dividing by the total number of kids who got Measles 1 / MR 1 from all months so far (i.e., 100 in Jan, 100 in Feb, and so on).

**Comment by cagulas** [comment]
@faith-mutua Testing scripts look good. Please go ahead and QA this issue.

**Comment by faith-mutua** [comment]
Results from QA on 7th Feb;

- [ ] Months are listed in reverse chronological order.

- [ ] Vaccinated numbers increase when a child is moved into the area

**Comment by faith-mutua** [comment]
Lgtm.

**Comment by cagulas** [comment]
- [ ] Make the Month row lighter font than the rest.

**Comment by cagulas** [comment]
This is done.
