### ISSUE TITLE
Add the coverage and dropout report menu options to the side bar

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#186]
![33329691-0b1c1e72-d42b-11e7-9569-3101337c7220](https://user-images.githubusercontent.com/3488986/33339229-cddccfc2-d478-11e7-8859-3c1eab56475c.png)

- [x] Add the coverage and dropout report menu options in the side bar.
- [x] Coverage and Dropout should go in between existing HIA2 and Stock menu options.
- [x] Coverage option opens the coverage report selection screen (https://github.com/OpenSRP/opensrp-client-path/issues/187).
- [x] Dropout option opens the dropout report selection screen (https://github.com/OpenSRP/opensrp-client-path/issues/176).

Assets are in [this issue](https://github.com/OpenSRP/opensrp-client-path/issues/170#issuecomment-347569772).

**Comment by cagulas** [comment]
Results from QA on 29 January (V1.3.2.1):

Nothing, lgtm!

**Comment by keymane** [comment]
@cagulas We've made the left side bar scrollable that is from ZEIR to Stock Control

**Comment by cagulas** [comment]
Lgtm
