### ISSUE TITLE
Handling locations with more than one tag

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-path#190]
See original related issue: https://github.com/OpenSRP/opensrp-client-path/issues/36

**Comment by faith-mutua** [comment]
@keymane health facility doesn't appear in the dropdowns on the birth registration form after service location has been assigned more than one tag.

**Comment by faith-mutua** [comment]
Results fro QA 13th April. 

Issue has passed QA

**Comment by cagulas** [comment]
Closing.
