### ISSUE TITLE
Child's GPS Location in the Edit Child Details Form

### ISSUE THREAD

**Issue by jasonrogena** [OpenSRP/opensrp-client-path#193]
Show a child's current saved GPS position in the edit child details form.

Related to https://github.com/onaio/kujaku/issues/22

**Comment by ekigamba** [comment]
PR on the library side.
ZEIR side already fixed in kujaku-dep branch https://github.com/OpenSRP/opensrp-client-path/commit/0edbeda1d00c84b7984714682280437912499021
