### ISSUE TITLE
Test children are downloading to Linda Clinic on production

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#202]
The PATH team is reporting that despite clearing data and syncing again for Linda Clinic, they are reporting that test data is appearing for users from Linda clinic. This seems to have started when the clinic had temporarily had two location tags in the system, but even though the duplicate tag was removed, the test child records are still appearing.

Here are some example test child cases that are downloading alongside the real data in Linda Clinic:

ZEIR IDs: 101284-8, 128998-2, and 128648-3

**Comment by cagulas** [comment]
They are also reporting that not all of the data for Linda clinic is downloading.

**Comment by keymane** [comment]
Moved all test patients to Happy clinic

**Comment by cagulas** [comment]
Seems to be fixed. Closing.
