### ISSUE TITLE
Clean up on HIA2 report form

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#21]
Leftover issues from https://github.com/OpenSRP/opensrp-client/issues/520 moved here:

- [x] Selecting the SAVE button on the HIA2 form shows a snackbar message that the changes have been saved. Text for snackbar message: "All changes saved."
- [x] The ID of the indicator should be shown in the form as well. See the "Name" column in the [reporting data dictionary](https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=2010018538). The ID can come before the indicator name, followed by a colon, e.g.: "CHN1-005: Attendance child health < 12 months (male)"
- [x] Summed indicators, e.g. "Attendance child health (total)", should not be editable as they sum numbers in the form. For a list of which indicators should not be editable, see the reporting data dictionary, "Formula" column. It will say if the indicator is summed and shouldn't be editable in the form.
- [x] The fields should only be required when submitting the form. If the user is just saving the form, some fields can be blank. Right now, you can't save the form unless all fields are not blank.

**Comment by faith-mutua** [comment]
Issue fixed
