### ISSUE TITLE
A deceased child appears in advanced search results

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#227]
This is dummy data on the test server.

Client `Sam Zuma` with ZEIR ID `1042613` apparently is deceased in OpenMRS (https://openmrs.zeir-stage.smartregister.org/openmrs/patientDashboard.form?patientId=45744&phrase=ma) but he appeared in advanced search results for biddemo user account.

**Comment by faith-mutua** [comment]
@keymane a deceased child still appears in advanced search results.

**Comment by faith-mutua** [comment]
This has passed QA
