### ISSUE TITLE
Update Kujaku library to latest version

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-path#228]
The latest version is 
- [x] 0.2.4-56-2
- [x] Update native form with bug fix for disappearing spinners
- [x] Update constants usage
- [x] Remove deprecated parcelables for the MapActivity
- [ ] Update Kujaku Config **NB: Later after this has been added by @jasonrogena PR https://github.com/onaio/kujaku/pull/47  & any related issues fixed**
- [x] When Offline mode is disabled, show a dilalog box asking whether to delete previously downloaded maps
- [x] Implement Info window double click
- [x] Implement Offline switch in BaseActivity

**Comment by cagulas** [comment]
@ekigamba said ok to close this.
