### ISSUE TITLE
OPV 4 showing as due when OPV 0 was given

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#243]
See below screenshot of dummy child Sally in biddemo account.

OPV 0 was given, yet it's showing that OPV 4 is currently due. If OPV 0 was given, OPV 4 should never be shown as due, and if OPV 4 is given, it should cancel out OPV 0 if it's not back-recorded yet.

![screenshot_20180212-124128](https://user-images.githubusercontent.com/3488986/36093158-dbdb485c-0ffa-11e8-8844-70c46f01fa45.png)

**Comment by ekigamba** [comment]
Issue cannot be replicated with the current version 1.3.2.1

Some of the affected children: 
- John Doe
- Sally Ndunda
- Sandra Owen

The alerts for OPV 4 vaccines in couch db for the above children have timestamps ranging from Nov 14, 2017 to February 7, 2018 GMT

**Comment by cagulas** [comment]
The issue now is that one cannot record OPV 4. If OPV 0 wasn't given, you don't mark that it was given, so it remains due. The problem is that since it remains due, it doesn't make OPV 4 become due, so the health worker can never actually record that OPV 4 was given.

So the check for OPV 4 should be that OPV 0 wasn't given and the child is at least 9 months old and OPV 3 was given at least 4 weeks ago. If all of those conditions are met, OPV 4 should become due. And yes, that will cause the situation where OPV 0 and OPV 4 are both showing as due at the same time. However, when the health worker marks one or the other, the other one would get canceled.

Is this feasible to do, or would it be more feasible to modify the birth registration form to ask a question for older kids whether OPV 0 was given or not?

**Comment by cagulas** [comment]
This is almost fixed, but I noticed something else in the 13 April release. At 9 months, when it shows both Measles 1 and OPV 4 due, if you only record Measles or MR 1 and don't record both vaccines at the same time, the OPV 4 reminder is canceled and you can't record it. This shouldn't happen. You should be able to record both at the same time or at separate times. But the cancellation of either OPV 0 or 4 seems to be working correctly.

**Comment by cagulas** [comment]
Lgtm
