### ISSUE TITLE
Refactor ZIER to use opensrp stock library

### ISSUE THREAD

**Issue by githengi** [OpenSRP/opensrp-client-path#249]
Refactor ZIER to use  [OpenSRP stock library](https://github.com/OpenSRP/opensrp-client-stock)

- [x] Move Stock UI

- [x] Move stock classes

- [x]  Move Stock config helper classes

- [x] Move  stock Database

- [x] Move Sync

- [x] Split PathJsonFormActivity move stock functionality to libary

- [x] Integrate ZIER left navigation with the stock library

**Comment by cagulas** [comment]
This is done, closing.
