### ISSUE TITLE
Update Sync Intervals

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-path#250]
Release
Sync - every 15 minutes
Weight, vaccine, recurring services - every 30 minutes
HIA2 - every hour
Coverage/Dropout - every hour
Image upload - every 3 hours
Pull unique IDs - every 3 hours

Debug
Sync - every 2 minutes
Weight, vaccine, recurring services - every 3 minutes
HIA2 - every 5 minutes
Coverage/Dropout - every 5 minutes
Image upload - every 7 minutes
Pull unique IDs - every 10 minutes

**Comment by cagulas** [comment]
This is done, closing.
