### ISSUE TITLE
Due dates for vaccines are not displaying 

### ISSUE THREAD

**Issue by jasonrogena** [OpenSRP/opensrp-client-path#28]
_From @faith-mutua on September 5, 2017 13:6_

Due vaccine column shows previous vaccines that have already been given to the patient. 

![screenshot_2017-09-05-16-02-47 1](https://user-images.githubusercontent.com/17847885/30062471-f6136300-9253-11e7-97e4-83c7febb450f.png)

_Copied from original issue: OpenSRP/opensrp-client#565_

**Comment by cagulas** [comment]
This is not an issue. The green ticks are supposed to show recently given vaccines.
