### ISSUE TITLE
A few issues on the Advanced Search page

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#280]
**Expected behavior**

- User should not be able to select Outside and inside My catchment area if there's no internet connection.
- User should not be able to uncheck all the Client status options. 
- After moving a child, the app should go back to the register view

**Actual behavior** 

- User can select Outside and inside My catchment area if there's no internet connection.
- User can uncheck all the Client status options. 
- After moving a child, the app stays on the Advanced Search page.

**Comment by cagulas** [comment]
Lgtm
