### ISSUE TITLE
Mother/guardian default DOB not displayed

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#282]
In the birth registration form, mother/guardian DOB field should have Jan/01/1960 as the default DOB and it should be editable. Currently, this field is blank.

**Comment by cagulas** [comment]
@faith-mutua Is this a new birth registration form or edit birth registration form? If it's a new one, the DOB field should be blank (the Jan 1, 1960 DOB gets populated only if no DOB is supplied and the form gets submitted). Can you add steps to reproduce for the issues that you're creating?

**Comment by faith-mutua** [comment]
@cagulas  this is for a new birth registration form.  Sorry for the mix up here. Let me close the issue.
