### ISSUE TITLE
Increase size of white background for user initials

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#29]
_From @cagulas on July 14, 2017 8:8_

For the initials MM, it cuts to the second line:

![screenshot_20170714-095633](https://user-images.githubusercontent.com/3488986/28203971-a664d486-6884-11e7-86c9-913f83688450.png)

_Copied from original issue: OpenSRP/opensrp-client#560_

**Comment by cagulas** [comment]
This is done.
