### ISSUE TITLE
Due vaccine column on the home register page is not being updated accordingly 

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-path#298]
Due vaccine column on the home register page doesn't seem to be updating after vaccines are given. Reference the child record that I shared on Slack channel. Measles 1 was given, yet the register view page still shows Overdue 9 months vaccines.

**Comment by cagulas** [comment]
Still not fixed in March 26 release

**Comment by cagulas** [comment]
April 13 release - passes QA

**Comment by cagulas** [comment]
This was done in last release. Closing.
