### ISSUE TITLE
Sync data based on team, not user

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#30]
_From @cagulas on July 12, 2017 16:50_

User A from a health facility only sees the data that she herself added (via birth registration form). If you clear data and log in as another user (user B) from that health facility, you see a different set of data (data that User B added herself). The data syncing should be based on team assignment, not user.

_Copied from original issue: OpenSRP/opensrp-client#557_

**Comment by cagulas** [comment]
This is done.
