### ISSUE TITLE
2018 year is not appearing in the dropdown for some coverage and dropout reports

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-path#300]
2018 year is not appearing in the dropdown for some coverage and dropout reports. 2018 should appear in Annual Coverage Reports - CSO and ZEIR since the current year is 2018. Right now, only 2016 and 2017 are appearing for both of these reports.

**Comment by cagulas** [comment]
This is fixed in the test release shared on 23 March
