### ISSUE TITLE
login bugs

### ISSUE THREAD

**Issue by keymane** [OpenSRP/opensrp-client-path#301]
Logging in - I'm often getting the login failed, check credentials, then the login failed, the server could not be reached messages. This happened when trying to log back in as the same user, but also trying to log in as another user from the same team.

See also this original issue https://github.com/OpenSRP/opensrp-client-path/issues/160 and also this issue https://github.com/OpenSRP/opensrp-client-path/issues/253

**Comment by cagulas** [comment]
I uninstalled the previous app and installed the 12 April app. I couldn't log in for about 10 minutes, as I was getting all of the login error messages mentioned in the original comment above.

**Comment by cagulas** [comment]
This is fixed, closing.
