### ISSUE TITLE
The expansion icon button in growth chart is not active yet

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#31]
_From @cagulas on July 12, 2017 8:15_

Moving from https://github.com/OpenSRP/opensrp-client/issues/469

I added an expansion icon button to the previous weights section of the growth chart. I think this can behave where either (A) the top portion (above the done button) gets longer or (B) the entire card contents get longer.

_Copied from original issue: OpenSRP/opensrp-client#556_

**Comment by cagulas** [comment]
This is done.
