### ISSUE TITLE
Alert button click in the register view opens the wrong vaccination dialog

### ISSUE THREAD

**Issue by ekigamba** [OpenSRP/opensrp-client-path#350]
How to replicate:

1. Open ZEIR, click on an activate alert button for any of the kids
2. The childs vaccination card will be openned & the vaccine immunization dialog for the earliest vaccine (the one indicated in the register view) should be openned. 

However, it opens vaccination dialogs for random vaccines

**Comment by cagulas** [comment]
Seems to be fixed.
