### ISSUE TITLE
Change how statuses (active, inactive, lost to follow-up) are displayed

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#37]
_From @cagulas on May 24, 2017 8:57_

We are changing how statuses are displayed in the app from an icon to a banner notification on the vaccine card page and the detailed view page. The reasoning for this is that there was no indication of the child's status on the vaccine card view, only the home screen and the detailed page. In addition, if the child is not active status, the user should be prevented from recording services to the child.

On the detailed view page:
- [x] Remove the status icon next to the child's name
- [x] Add the banner message to show the child's status. If the child's status is active, there is no reason to show the banner message. Only show the banner message if the child's status is inactive or lost to followup.

![228342443](https://cloud.githubusercontent.com/assets/3488986/26394608/eb5ac094-4086-11e7-8f87-118c87bb9a58.png)

Text for the banner messages:
- Status: Inactive
- Status: Lost to Follow-Up

On the vaccine card page:

![228342075](https://cloud.githubusercontent.com/assets/3488986/26394638/fd0dad1a-4086-11e7-96be-c106fd770c8c.png)

- [x] Add the banner message to show the child's status. If the child's status is active, there is no reason to show the banner message. Only show the banner message if the child's status is inactive or lost to followup.
- [x] The page is slightly greyed out to indicate the services cannot be recorded (see mockup above).
- [x] If the user taps anywhere outside the demographic details box, the sibling box, or the top action bar, the following message appears:
![228342068](https://cloud.githubusercontent.com/assets/3488986/26394665/1c57e3c0-4087-11e7-9812-a149c876c073.png)

- [x] Cancel or tapping anywhere outside the message closes it without any changes.
- [x] Selecting "Make Active" changes the child's status to active and submits the encounter to OpenMRS to change the concept in OMRS to active as well.

Text for the message:

This child's status is [inactive / lost to follow-up]. Make [her / him] active?
Making the child active will resume the ZEIR service schedules and lets you record services.

_Copied from original issue: OpenSRP/opensrp-client#515_

**Comment by cagulas** [comment]
Let's also make all the options in the edit menu greyed out and not tappable (excluding the change status menu option) when the child is inactive or lost to followup.

**Comment by ekigamba** [comment]
@cagulas What about the weight graph button? Should it be clickable to show the Z-score graph and previous weights?

**Comment by cagulas** [comment]
I think it's ok to keep allowing the weight graph to be viewed.

**Comment by rowo** [comment]
@vincent-karuri

**Comment by cagulas** [comment]
Results from 13 April 2018 release QA:

- [ ] The Updating popup spinner when you change the status takes a few seconds to update. Are there any quick performance improvements we can make to this? 

Otherwise, looks really good.

**Comment by cagulas** [comment]
Think we can close this. Performance is not really an issue, unless it gets worse.
