### ISSUE TITLE
Weight button and undo vaccine buttons disappear too soon on vaccine card view

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#39]
_From @cagulas on May 19, 2017 7:45_

- [ ] The undo button next to a vaccine that was just given in the vaccine card view is disappearing too soon. I think it's supposed to show for a period of 24 hours; instead, the undo button disappears after a few minutes.

- [ ] Similarly, the record weight button on the vaccine card is resetting too soon - I was able to record weight for a child a few minutes after I recorded it the first time. I think we need to add an "undo" for weight as well, allowing the user to edit or undo weight for a period of 24 hours, then it resets to "Record weight" button again.

I know there was back and forth between resetting after 12 hours vs. 24 hours. I think we should keep it consistent throughout the app for all services, including vaccines, recurring services, weight, etc. I am fine with 12 hours, unless there are objections.

Putting this in the clean up milestone. @maina I think you mentioned this is dependent on the undo operation in the server?

_Copied from original issue: OpenSRP/opensrp-client#510_

**Comment by cagulas** [comment]
Closing, more recent issue is here: https://github.com/OpenSRP/opensrp-client-path/issues/283
