### ISSUE TITLE
Create Stock usage DHIS2 Dashboard report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#45]
_From @tobiasmakai on April 5, 2017 14:58_

**Description**
On demand visual of the amount of stock used within a specified date period for each antigen.

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick needed elements for the calculated stock used in DHIS2
2. Define chart parameters
3. Create DHIS2 chart
4. Place chart into Immunization DHIS2 Dashboards

_Copied from original issue: OpenSRP/opensrp-client#467_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
