### ISSUE TITLE
Create Stock balance DHIS Dashboard report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#46]
_From @tobiasmakai on April 5, 2017 14:53_

**Description**
On demand visual of the balance of stock in doses and vials relative to the minimum/reorder level for that antigen.

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick needed elements of the calculated stock balance from DHIS2
2. Define chart parameters
3. Create chart
4. Place chart into DHIS2 Immunization Dashboards

_Copied from original issue: OpenSRP/opensrp-client#466_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
