### ISSUE TITLE
Create Total not gaining weight < 5 years DHIS2 Dashboard report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#47]
_From @tobiasmakai on April 5, 2017 14:46_

**Description**
Month to month visual of the number of total children < five years who were weighed for 2 consecutive months who did not gain >100g of weight in those months.

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick needed elements for calculated total number of children under 5 not gaining weight from DHIS2.
2. Define chart parameters
3. Create chart
4. Place chart into  Immunization DHIS2 Dashboards

_Copied from original issue: OpenSRP/opensrp-client#465_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
