### ISSUE TITLE
Create Total attendance child health DHIS2 Dashboard report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#48]
_From @tobiasmakai on April 5, 2017 14:37_

**Description**
Month to month visual of the total number of children < 5 who attended clinic that month

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick needed elements for the calculated total child attendance from DHIS2
2. Define chart parameters 
3. Create chart
4. Place chart into DHIS2 Immunization Dashboards

_Copied from original issue: OpenSRP/opensrp-client#464_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
