### ISSUE TITLE
Create Annual Coverage DHIS2 Dashboard reports

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#49]
_From @tobiasmakai on April 5, 2017 14:29_

**Description**
Year to year visual of the percentage of fully-immunized children (For particular vaccine) > one year compared to the total number of surviving children > one year in the target population.

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick required elements for calculated annual coverage rates from DHIS2
2. Define chart parameters
3. Create DHIS2 chart 
4. Place chart into DHIS2 Immunization Dashboards

_Copied from original issue: OpenSRP/opensrp-client#463_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
