### ISSUE TITLE
Create Cohort coverage DHIS2 Dashboard report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#50]
_From @tobiasmakai on April 5, 2017 14:21_

**Description**
Month to month visual of the percentage of children < one year born/living within the home facility location, born in a specific time-frame and  vaccinated with a specific vaccine dose.

**Dashboards Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick required elements for vaccine indicators for specific timeframes from DHIS2
2. Define chart parameters
3. Create DHIS2 chart
4. Place chart into Immunization DHIS2 dashboards

_Copied from original issue: OpenSRP/opensrp-client#462_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
