### ISSUE TITLE
Create Days with no stock out DHIS2 Dashboard report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#51]
_From @tobiasmakai on April 5, 2017 14:10_

**Description**
Number of days the facility has been stocked with all antigens

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick needed elements for stock from DHIS2
2. Define chart parameters
3. Create DHIS2 chart
4. Place chart into the Immunization DHIS2 Dashboards

_Copied from original issue: OpenSRP/opensrp-client#461_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
