### ISSUE TITLE
Create Rate of fully immunised children DHIS2 Dashboard report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#52]
_From @tobiasmakai on April 5, 2017 14:0_

**Description**
Month to month visual number of children < one year who have received the complete BCG, OPV series, DPT-Hib+Hep1 series, PCV series , RV series and measles/MR 1 within 10 days of each antigen being due as a proportion of the facility's <1 target population

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick required elements for the indicators from DHIS2
2. Define chart parameters
3. Create DHIS2 Chart
4. Place chart into Immunization DHIS2 Dashboards

_Copied from original issue: OpenSRP/opensrp-client#460_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
