### ISSUE TITLE
Create Number of births DHIS2 Dashboard report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#53]
_From @tobiasmakai on April 5, 2017 13:48_

**Description**
Month to month visual of the number of births recorded as having occurred at a particular facility.

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick elements of calculated number of births recorded at the facility in DHIS2
2. Define parameters
3. Create DHIS2 Chart
4. Place chart into Immunization DHIS2 Dashboards

_Copied from original issue: OpenSRP/opensrp-client#459_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
