### ISSUE TITLE
Create Number of Penta dropouts DHIS2 Dashboard report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#54]
_From @tobiasmakai on April 5, 2017 13:25_

**Description**
A month to month visual of the comparison of the number of children who received Penta1 but did not return for Penta3 when it was due.

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick needed elements for the calculated Penta1 to Penta3 dropouts in DHIS2
2. Define parameters
3. Create DHIS2 Chart
4. Place chart into DHIS2 Dashboard

_Copied from original issue: OpenSRP/opensrp-client#458_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
