### ISSUE TITLE
Create Penta dropout rate DHIS2 Dashboard report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#56]
_From @tobiasmakai on April 5, 2017 13:10_

**Description**
Month to month visual comparison between number of children who start the immunization schedule against the number who complete it.

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick elements for calculated Penta1 to Penta3 dropout rate in DHIS2.
2. Define required parameters
3. Create DHIS2 charts
4. Place chart into DHIS2 Dashboards

_Copied from original issue: OpenSRP/opensrp-client#456_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
