### ISSUE TITLE
Create BCG-Mealses/MR Dropout Rate  DHIS2 Dashboard report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#57]
_From @tobiasmakai on April 5, 2017 13:0_

**Description**
Month to month visual comparison between number of children who start the immunization schedule against the number who complete it.

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick needed elements for the calculated BCG to Measles dropout rate in DHIS2
2. Define parameters
3. Create DHIS2 Chart
4. Place chart into DHIS2 Dashboard

_Copied from original issue: OpenSRP/opensrp-client#455_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
