### ISSUE TITLE
Create Stock out days DHIS2 Dashboard report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#58]
_From @tobiasmakai on April 5, 2017 10:46_

**Description**
A month to month visual display of the number of days the facility could not administer vaccines because the vaccine was out of stock.

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick needed elements for the counted stock out days in DHIS2
2. Define parameters
3. Create DHIS2 Chart
4. Place chart into DHIS2 Dashboard

_Copied from original issue: OpenSRP/opensrp-client#454_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
