### ISSUE TITLE
Create Vaccine wastage DHIS2 Dashboard report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#59]
_From @tobiasmakai on April 5, 2017 10:11_

**Description**
A monthly visual display of the number of vaccine doses that are issued to a health facility but are not administered to the children.

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick needed elements for calculated stock wastage indicators in DHIS2
2. Define parameters
3. Create DHIS2 Chart for trend analysis
4. Place chart into DHIS2 Dashboard

_Copied from original issue: OpenSRP/opensrp-client#453_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
