### ISSUE TITLE
Create On-time Vaccination DHIS2 Dashboard 

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#60]
_From @tobiasmakai on April 5, 2017 9:5_

**Description**
A measure of timelines in the delivery of the correct vaccine at the correct time to each and every child that was in need of a vaccination.

**Dashboard Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=755434359

**Steps**
1. Pick needed elements for calculated indicator from DHIS2
2. Define chart parameters 
3. Create DHIS2 chart
4. Place into Immunization DHIS2 Dashboard

_Copied from original issue: OpenSRP/opensrp-client#452_

**Comment by cagulas** [comment]
This is out of scope for the project. Closing.
