### ISSUE TITLE
Add Penta dropout Report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#66]
_From @geoffreymuchai on April 4, 2017 9:29_

**Description**
Comparison between number of infants who start the immunization schedule against the number who complete it.

**Report Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=1991837752

_Copied from original issue: OpenSRP/opensrp-client#451_

**Comment by cagulas** [comment]
Closing this for now. We will create a new issue when the report is ready to implement.
