### ISSUE TITLE
Add growth/weight alert functionality to vaccine card view

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#71]
_From @cagulas on May 9, 2017 8:10_

After recording weight, the app will show an alert based on the child's growth trajectory. Z-score will also be displayed in the alert, see mockups below.

There are three alerts based on whether the child has gained weight from the last weigh-in, lost weight, or not gained any weight.

**Gained weight**
No mockup provided (see the one below). The message after weight and z-score will be "Good trend: child is growing well"

**No weight gain**
![232735912](https://cloud.githubusercontent.com/assets/3488986/25841150/a857f702-34a7-11e7-98c3-5855f2b978cc.png)

**Lost weight**
No mockup provided (see the one above). The message after weight and z-score will be "Very dangerous trend: child may be ill, needs extra care

_Copied from original issue: OpenSRP/opensrp-client#493_

**Comment by cagulas** [comment]
This is out of scope for now. Closing for now.
