### ISSUE TITLE
Add the Facility Cummulative Coverage Report 

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#73]
_From @geoffreymuchai on April 4, 2017 9:24_

**Description**
Cumulative monthly percentage of eligible fully-immunized infants (For particular vaccine)compared to the cumulative number of surviving infants in the target population for a particular type period. The immunization coverage rate is measured by comparing the cumulative number of doses actually given per month for the number of months under consideration and the cumulative monthly number of the target population of surviving infants under one year of age (these are the eligible infants). The result is expressed as a percentage and charted on a graph.

This graph report has the following elements:

Title: *Immunization Monitoring Chart*

**At the top of the report above the X axis in the same line**
Area name
Year
Total Catchment Population
Total Population < 1
Monthly Target < under 1 [Total population < 1/12]

**On the X axis at the bottom**
Jan | Feb | Mar | Mar | Apr | May | Jun | Jul | Aug | Sep | Oct | Nov | Dec |

**On the left Y axis**
Cumulative target population < 1

**On the right Y**
Percentages starting from 0 and increasing in 10s upto 100%

At the bottom of the graph a table: 
**Top row**
Months Jan | Feb | Mar | Mar | Apr | May | Jun | Jul | Aug | Sep | Oct | Nov | Dec | (same months as above)

**First column with:**
Total immunized dose 1
Total immunized dose 3
Cum total immunized dose 1
Cum total immunized dose 3
Drop out No. Dose 1-Dose 3
Drop out % (Dose 1 - Dose 3 / Dose 1 * 100)

The remaining columns are monthly values for the indicators in the first column.

**Reporting Data Dictionary**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=705615058

_Copied from original issue: OpenSRP/opensrp-client#449_

**Comment by cagulas** [comment]
Closing this for now. We will create a new issue when the report is ready to implement.
