### ISSUE TITLE
Add the Annual Coverage Report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#74]
_From @geoffreymuchai on April 4, 2017 9:18_

**Description**
Percentage of eligible fully-immunized infants (For particular vaccine)compared to the total number of surviving infants in the target population. The immunization coverage rate is measured by comparing the number of doses actually given and the number in the target population of surviving infants under one year of age (these are the eligible infants). The result is expressed as a percentage.

Essentially
**Immunization coverage rate** (for a particular vaccine) = number receiving all doses ÷ number in the target population x 100

**Number receiving all doses is:** Number of surviving infants under one year of age receiving all the required doses during the previous 12 months for the selected vaccine

**Target population is:** Total number of surviving infants at the start of that reporting period as provided by CSO(Central statistics Office)

**Report Data Definition**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=705615058

_Copied from original issue: OpenSRP/opensrp-client#448_

**Comment by cagulas** [comment]
Closing this for now. We will create a new issue when the report is ready to implement.
