### ISSUE TITLE
Add the Cohort Coverage Report

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#76]
_From @geoffreymuchai on April 4, 2017 9:14_

**Description**
Vaccination coverage as the percentage of the children living in a certain area, that were born in a certain timeframe, and that were vaccinated with a certain vaccine dose (cohort reporting).

**Report Data Definition**
https://docs.google.com/spreadsheets/d/1qZCTBqCz2IBB4s8siKTKgm68lA_oRdrkLvNTbFiGFhc/edit#gid=705615058

_Copied from original issue: OpenSRP/opensrp-client#447_

**Comment by cagulas** [comment]
Closing this for now. We will create a new issue when the report is ready to implement.
