### ISSUE TITLE
Test CouchDB Sync performance

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#78]
_From @mberg on February 7, 2017 12:54_

Do some testing to ensure scalability of CouchSync.

Two things we need to test.  One is how sync works when there are a lot of records and how sync works when there is a lot of concurrent clients.

_Copied from original issue: OpenSRP/opensrp-client#397_

**Comment by faith-mutua** [comment]
_From @cagulas on February 7, 2017 16:42_

@mberg what milestone should this go in?

**Comment by faith-mutua** [comment]
_From @cagulas on June 26, 2017 13:19_

@maina can we close this issue?

**Comment by faith-mutua** [comment]
_From @pld on June 26, 2017 14:10_

Have we run tests on this? Can we automate the tests for this?

**Comment by cagulas** [comment]
We moved from cloudant to REST API. Closing this.
