### ISSUE TITLE
BZ7.8 Flag duplicate records that require manual review

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#79]
_From @cagulas on January 4, 2017 21:34_

- [ ] Need business rules for flagging possible duplicate records 
- [ ] Need UI for where these would be viewed and then merged

Am assuming they mean client records and not event or encounter records.

_Copied from original issue: OpenSRP/opensrp-client#353_

**Comment by cagulas** [comment]
Old issue. Closing.
