### ISSUE TITLE
BZ6.5 Implement support for discarding events

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#81]
_From @cagulas on January 4, 2017 21:24_

- [ ] Need clarity on what this means, i.e. use cases for this. Probably want to combine with feature that allows events to be merged, i.e., some sort of admin interface for managing, merging, deleting events.

_Copied from original issue: OpenSRP/opensrp-client#348_

**Comment by cagulas** [comment]
Old issue. Closing for now.
