### ISSUE TITLE
BZ3.4 Support an audit trail when event records are merged

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#82]
_From @cagulas on January 4, 2017 19:47_

- [ ] Would this only be handled in OpenMRS? If not, what parameters would be used to identify possible duplicate events? What mechanism would be used to merge them?
- [ ] Similar to BZ3.3, need to identify where audit trails would be viewed.

_Copied from original issue: OpenSRP/opensrp-client#321_

**Comment by cagulas** [comment]
Old issue, closing.
