### ISSUE TITLE
BZ3.3 Trace and record changes to data taken by the system and by users (update/delete/add)

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#83]
_From @cagulas on January 4, 2017 19:43_

- [ ] Need list of information to be contained in audit trail
- [ ] Need to clarify what "by the system" means
- [ ] Develop mechanism for maintaining data audit trails and where this can be viewed

_Copied from original issue: OpenSRP/opensrp-client#320_

**Comment by cagulas** [comment]
Old issue, closing.
