### ISSUE TITLE
BZ2.6 Warn user if a child is being registered with the same mother/guardian name, last name, date of birth, and gender as an already registered child

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#84]
_From @cagulas on January 4, 2017 19:23_

From requirements, first name is optional, so should this be based on surname, DOB, and gender only?

- [ ] Need to confirm if this search is only on existing records on the device or entire client database. i.e., does it require an online connection. 

_Copied from original issue: OpenSRP/opensrp-client#315_

**Comment by faith-mutua** [comment]
_From @rowo on January 19, 2017 6:28_

I think we should assume that a connection might not be present and yet it's critical to always allow someone to do their job. In the case, and this is easier said than done,, we can/should have the app search the device records, and if/when there is a connection and there's an error where this info matches, we need to figure out a way to notify and allow fixes/merge.

This is also tough because potentially you might not learn about this error until after a form is submitted, so you might do some useless work, which is one thing this issue is trying to prevent.

**Comment by faith-mutua** [comment]
_From @cagulas on January 19, 2017 6:48_

In subsequently reading the requirements, there is emphasis on being able to merge patient records (req 7.8), so I think the assumption is duplicate records will inevitably happen, this is just to stop it from happening more.

**Comment by faith-mutua** [comment]
_From @maina on January 19, 2017 7:3_

Is a combination of first name, last name, date of birth, and gender really good enough for avoiding duplicates? I guess not

**Comment by faith-mutua** [comment]
_From @cagulas on February 1, 2017 7:18_

This is ready to be worked on. When a nurse is filling the birth registration form, if the `Mother_Guardian_Name`, `Last_Name`, `Date_Birth`, AND `Sex` fields are the same as another child, give warning that another child exists with this same info.

**Comment by cagulas** [comment]
Old issue, closing.
