### ISSUE TITLE
Simplify ZEIR vaccine grouping

### ISSUE THREAD

**Issue by faith-mutua** [OpenSRP/opensrp-client-path#88]
_From @rowo on April 11, 2017 1:22_

A bit cleaner

![groupings-restyle](https://cloud.githubusercontent.com/assets/1584163/24888785/b815d0e0-1e33-11e7-8f92-e5649d62f543.png)

_Copied from original issue: OpenSRP/opensrp-client#476_

**Comment by cagulas** [comment]
Looks good to me.
