### ISSUE TITLE
Temporarily remove some date constraints for back vaccine data entry

### ISSUE THREAD

**Issue by cagulas** [OpenSRP/opensrp-client-path#98]
This change is the result of observation and feedback from the teams on how difficult it is for users to back record vaccines that didn't strictly adhere to vaccine schedules. For older children who need to be registered in the app and have their previous vaccine history recorded, the date constraints are too strict and do not allow them to record the vaccines when they were actually given. Since the emphasis needs to be on getting the children registered in the app, this is a real impediment to uptake.

As a result, we have decided to temporarily remove certain date constraints on the back entry of vaccine data. These are temporary, i.e. the constraints likely will be added back in the future, so if there's a way to just comment out the date constraints, that would be great.

Importantly, we are keeping the following two date constraints (ie., do not remove them):
- No vaccine can be recorded before the child's DOB
- No vaccine can be recorded after today's date
- All other data constraints can be commented out for now

Is it possible to do this only for older children who need vaccines back recorded or must this change apply to all children?

**Comment by ekigamba** [comment]
After the constraints are removed, the service provider seems to be able to give a later vaccine before than the earlier-one eg. **_OPV 2 can be given before OPV 1_** however if _**OPV 1 is given today you cannot give OPV 2**_.

Should this stay as-is for the time being?

Look at the below screenshots in 6 weeks and 10 weeks for OPV 1 & OPV 2.

This is the updated app without the constraints.

![screenshot_20171006-092254](https://user-images.githubusercontent.com/31766075/31265654-9ab7403e-aa78-11e7-9387-af7a57999131.png)
![screenshot_20171006-092309](https://user-images.githubusercontent.com/31766075/31265653-9ab47228-aa78-11e7-9ee3-b8f9641bc93b.png)

**Comment by cagulas** [comment]
Yes, this is ok for now.
